language: ruby
rvm:
  - 2.2.2
addons:
  postgresql: "9.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y beanstalkd
install:
  - bundle install
before_script:
  - createdb ebicsbox_test
  - sequel -m migrations postgres://localhost/ebicsbox_test
  - beanstalkd &
script:
  - bundle exec rspec spec
