language: ruby
sudo: false
cache:
  - bundler
  - apt
stages:
  - test
  - build
services:
  - redis-server
  - docker
addons:
  postgresql: "9.6"
jobs:
  include:
    - stage: test
      language: ruby
      rvm: 2.5.1
      services:
        - redis-server
      addons:
        postgresql: "9.6"
      env:
        - RACK_ENV=test
      before_script:
        - createdb ebicsbox_test
        - bundle exec bin/migrate
      script:
        - bundle exec rspec spec

    - stage: build
      language: minimal
      cache: false
      install: skip
      before_script:
        - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
      script:
        - docker build -t ebicsbox:latest .
        - docker tag ebicsbox:latest railslove/ebicsbox:latest
        - docker push railslove/ebicsbox:latest
      branches:
        only:
          - master

    - stage: build
      language: minimal
      cache: false
      install: skip
      before_script:
        - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
      script:
        - docker build -t ebicsbox:$TRAVIS_TAG .
        - docker tag ebicsbox:$TRAVIS_TAG railslove/ebicsbox:$TRAVIS_TAG
        - docker push railslove/ebicsbox:$TRAVIS_TAG
      on:
        tags: true

notifications:
  slack:
    on_success: change
    on_failure: always
    secure: hQ448PKksVM8tscDzphg/QZvpRrnowFNJq/zNMqZg1GtYJ+Rxpf0hEYg3COx628xzCclEre90+QX7VnZbyL+rrtaYTV8r05/tQ344kDfRKUZlNTPrnCasm0mpmTuT1b8hbSzOH2JkUqgKpm76Kl3CVm6RLVH/E2NEBhj4pC2eS8=
