version: "3.7"
networks:
  ebicsbox_network:
services:
  web:
    image: railslove/ebicsbox
    restart: always
    env_file:
      - .env
      - .web.env
    expose:
      - 5000
    environment:
      - VIRTUAL_PORT=5000
    networks:
      - ebicsbox_network
    command: bundle exec rackup -p 5000 -o 0.0.0.0
    depends_on:
      - proxy
  worker:
    image: railslove/ebicsbox
    restart: always
    env_file: .env
    command: bundle exec sidekiq -C ./config/sidekiq.yml -r ./config/sidekiq.rb
    networks:
      - ebicsbox_network
  proxy:
    image: jwilder/nginx-proxy
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /tmp/certs:/etc/nginx/certs:ro
      - /tmp/html:/usr/share/nginx/html:rw
      - /tmp/vhost.d:/etc/nginx/vhost.d
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - ebicsbox_network
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /tmp/html:/usr/share/nginx/html:rw
      - /tmp/vhost.d:/etc/nginx/vhost.d:rw
      - /tmp/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - proxy
    networks:
      - ebicsbox_network
