version: "3"
services:
  redis:
    image: redis
    restart: always
  web:
    image: railslove/ebicsbox
    restart: always
    env_file:
      - .env
      - .web.env
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - 5000:5000
    command: bundle exec puma ./config.ru -p 5000
    depends_on:
      - redis
      - proxy
  worker:
    image: railslove/ebicsbox
    restart: always
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379
    command: bundle exec sidekiq -C ./config/sidekiq.yml -r ./config/sidekiq.rb
    depends_on:
      - redis
  scheduler:
    image: railslove/ebicsbox
    restart: always
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379
    command: bundle exec clockwork config/scheduler.rb
    depends_on:
      - redis
  proxy:
    image: jwilder/nginx-proxy
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /tmp/certs:/etc/nginx/certs:ro
      - /tmp/html:/usr/share/nginx/html:rw
      - /tmp/vhost.d:/etc/nginx/vhost.d
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    ports:
      - 80:80
      - 443:443
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /tmp/html:/usr/share/nginx/html:rw
      - /tmp/vhost.d:/etc/nginx/vhost.d:rw
      - /tmp/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - proxy
