db:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=mysecretpassword
    - POSTGRES_USER=ebicsbox
  expose:
    - "5432"
  volumes:
    - /data-postgresql:/var/lib/postgresql/data
queue:
  image: michaelcontento/beanstalkd
  expose:
    - "11300"
  volumes:
    - /data-beanstalkd:/data
app:
  image: ebicsbox:0.7.1
  environment:
    - USERNAME=ebics
    - PASSWORD=istsuper
    - "BEANSTALKD_URL=queue:11300"
    - "DATABASE_URL=postgresql://db/ebicsbox?user=ebicsbox&password=mysecretpassword"
    - "PORT=5000"
    - "RACK_ENV=production"
    - "VIRTUAL_HOST=ebicsbox"
    - "PASSPHRASE=asdasdasdasdasd"
    - "SECRET_TOKEN=sehrlangersecrettokenistsecret1234"
  links:
    - db
    - queue
  expose:
    - "5000"
  command: "bin/start all"
proxy:
  image: jwilder/nginx-proxy:latest
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  links:
    - "app:ebicsbox"
  ports:
    - "80:80"
    - "443:443"
