version: '3'
services:
  db:
    image: postgres:9.6.1-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=ebicsbox
    expose:
      - 5432
  webapp:
    environment:
      - DATABASE_URL=postgresql://db/ebicsbox?user=ebicsbox&password=mysecretpassword
    depends_on:
      - db
