db:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=mysecretpassword
    - POSTGRES_USER=ebicsbox
  expose:
    - "5432:5432"
  volumes:
    - /data-postgresql:/var/lib/postgresql/data
queue:
  image: michaelcontento/beanstalkd
  expose:
    - "11300:11300"
app:
  image: ebicsbox:0.1.14
  environment:
    - USERNAME=ebics
    - PASSWORD=istsuper
    - "BEANSTALKD_URL=queue:11300"
    - "DATABASE_URL=jdbc:postgresql://db/ebicsbox?user=ebicsbox&password=mysecretpassword"
    - "JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom"
    - "JRUBY_OPTS=-J-Xmx512m"
    - "PORT=5000"
    - "RACK_ENV=production"
    - "VIRTUAL_HOST=ebicsbox"
  links:
    - db
    - queue
  expose:
    - "5000:5000"
  command: "bin/start server"
clock:
  image: ebicsbox:0.1.14
  environment:
    - USERNAME=ebics
    - PASSWORD=istsuper
    - "BEANSTALKD_URL=queue:11300"
    - "DATABASE_URL=jdbc:postgresql://db/ebicsbox?user=ebicsbox&password=mysecretpassword"
    - "JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom"
    - "JRUBY_OPTS=-J-Xmx512m"
  links:
    - db
    - queue
  command: "bin/start clock"
worker:
  image: ebicsbox:0.1.14
  environment:
    - USERNAME=ebics
    - PASSWORD=istsuper
    - "BEANSTALKD_URL=queue:11300"
    - "DATABASE_URL=jdbc:postgresql://db/ebicsbox?user=ebicsbox&password=mysecretpassword"
    - "JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom"
    - "JRUBY_OPTS=-J-Xmx512m"
  links:
    - db
    - queue
  command: "bin/start worker"
proxy:
  image: jwilder/nginx-proxy:latest
  volumes:
    - /Users/yoyostile/Desktop/certs:/etc/nginx/certs
    - /var/run/docker.sock:/tmp/docker.sock:ro
  links:
    - "app:ebicsbox"
  ports:
    - "80:80"
    - "443:443"
